version: "3.9"

services:
  taskevalpro-db:
    image: postgres:15-alpine
    container_name: taskevalpro-db
    ports:
      - '5432:5432'  # Map container port 5432 to host port 5432 for access
    environment:
      POSTGRES_DB: taskevalpro  # Database name
      POSTGRES_USER: postgres  # Username
      POSTGRES_PASSWORD: password  # Password (consider using environment variables for security)
      POSTGRES_HOST_AUTH_METHOD: trust  # Authentication method (consider using a stronger method in production)
    logging:
      options:
        max-size: 10m  # Maximum log file size
        max-file: "3"  # Maximum number of log files
    volumes:
      - ./postgres-data:/var/lib/postgresql/data  # Persist database data
      - ./scripts/ddl.taskevalpro.sql:/docker-entrypoint-initdb.d/01_ddl.sql
      - ./scripts/dml.taskevalpro.sql:/docker-entrypoint-initdb.d/02_dml.sql
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -q -d taskevalpro -U postgres" ]  # Health check for Postgres
      interval: 10s  # Check interval
      timeout: 10s  # Check timeout
      retries: 5  # Number of retries before considering unhealthy
